# Generated by Django 6.1 on 2026-09-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(default='9360484136', max_length=20)),
                ('phone2', models.CharField(default='9894010163', max_length=20)),
                ('email', models.EmailField(default='zeroonessecurity@gmail.com', max_length=254)),
                ('address', models.TextField(default='61, Indhira Nagar, Near Aavin Junction, K.K Nagar, Madurai - 20.')),
                ('hero_title', models.CharField(default='Complete Security & IT Solutions Under One Roof', max_length=255)),
                ('about_text', models.TextField(default='Zero Ones Security System is a trusted provider of CCTV cameras, Biometric devices...')),
            ],
        ),
    ]
