# Generated by Django 6.1 on 2026-09-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mission_text',
            field=models.TextField(default='To deliver reliable products, professional services and continuous support to our customers.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='values_text',
            field=models.TextField(default='Trust, Quality, Customer Satisfaction and Long-term Relationships.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vision_text',
            field=models.TextField(default='To create safer and smarter environments with advanced security and technology solutions.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
