# Generated by Django 6.1 on 2026-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesetting_facebook_url_sitesetting_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Zero Ones Security System', max_length=255)),
                ('description', models.TextField(default='Zero Ones Security System is a trusted provider of CCTV cameras, Biometric devices, and complete IT security solutions.')),
                ('vision', models.TextField(default='To create safer and smarter environments with advanced security and technology solutions.')),
                ('mission', models.TextField(default='To deliver reliable products, professional services and continuous support to our customers.')),
                ('values', models.TextField(default='Trust, Quality, Customer Satisfaction and Long-term Relationships.')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(default='9360484136', max_length=20)),
                ('phone2', models.CharField(default='9894010163', max_length=20)),
                ('email', models.EmailField(default='zeroonessecurity@gmail.com', max_length=254)),
                ('address', models.TextField(default='61, Indhira Nagar, Near Aavin Junction, K.K Nagar, Madurai - 20.')),
                ('working_hours', models.CharField(default='Monday - Saturday, 9:00 AM - 7:00 PM', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Your trusted partner for complete security and IT solutions in Madurai.')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('whatsapp_url', models.URLField(blank=True, default='')),
                ('copyright_text', models.CharField(default='Zero Ones Security System. All Rights Reserved.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Complete Security & IT Solutions Under One Roof', max_length=255)),
                ('subtitle', models.CharField(default='Sales | Installation | Service | Maintenance | Support', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='ZERONES', max_length=100)),
                ('tagline', models.CharField(default='SECURITY SYSTEM Madurai', max_length=150)),
                ('quote_label', models.CharField(default='Get a Quote', max_length=100)),
            ],
        ),
    ]
