# Generated by Django 6.1 on 2026-09-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutsection_contactsection_footersection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='contactsection',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Hero'},
        ),
        migrations.AlterModelOptions(
            name='navbarsection',
            options={'verbose_name': 'Navbar', 'verbose_name_plural': 'Navbar'},
        ),
    ]
