# Generated by Django 6.1 on 2026-09-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A Simple Process From Requirement to Installation', max_length=255)),
                ('step1', models.CharField(default='Share Your Requirement — Tell us about your property, workplace, vehicle or business requirement.', max_length=255)),
                ('step2', models.CharField(default='Understand Your Needs — We evaluate relevant factors such as coverage, usage, number of users, vehicle type or operational requirements.', max_length=255)),
                ('step3', models.CharField(default='Recommend a Suitable Solution — We help you understand relevant products and configurations based on your actual requirement.', max_length=255)),
                ('step4', models.CharField(default='Install & Configure — Our team assists with installation, configuration and basic system testing based on the selected solution.', max_length=255)),
                ('step5', models.CharField(default='Get Support — After setup, relevant guidance and support are provided based on the product or service requirement.', max_length=255)),
            ],
            options={
                'verbose_name': 'How It Works',
                'verbose_name_plural': 'How It Works',
            },
        ),
    ]
