# Generated by Django 6.1 on 2026-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_testimonial_trustedbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='button_label',
            field=models.CharField(default='Request a Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='description',
            field=models.TextField(default='Have a requirement for CCTV, security cameras, biometric attendance, vehicle tracking or cash counting? Share your requirement with Zero Ones and our team can help you identify a suitable solution based on your needs.'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='heading',
            field=models.CharField(default='Find the Right Security & Technology Solution in Madurai', max_length=255),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='support_items',
            field=models.TextField(default='CCTV Installation\nCCTV Setup & Configuration\nCCTV Repair & Maintenance\nBiometric Attendance\nGPS Vehicle Tracking\nCash Counting Machines\nOther Relevant Technology Requirements'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='support_title',
            field=models.CharField(default='We Support Requirements Related To', max_length=255),
        ),
    ]
