# Generated by Django 6.1 on 2026-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contactsection_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_label',
            field=models.CharField(default='Explore Solutions', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='considerations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
