# Generated by Django 6.1 on 2026-09-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_product_button_label_product_considerations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='button_label',
            field=models.CharField(default='Request Service', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='considerations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
