# Generated by Django 6.1 on 2026-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_service_button_label_service_considerations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='A Practical Approach to Security & Technology Solutions', max_length=255)),
                ('description', models.TextField(default='Zero Ones focuses on understanding the requirement first, recommending a suitable solution and providing relevant installation, configuration and support.')),
                ('point1', models.CharField(default='Requirement First — We start by understanding your actual requirement before recommending a product or system.', max_length=255)),
                ('point2', models.CharField(default='Suitable Product Guidance — Different homes, workplaces, vehicles and businesses require different specifications. We help you understand relevant options before planning.', max_length=255)),
                ('point3', models.CharField(default='Professional Installation — Our support extends beyond product selection to installation, configuration and basic system testing where applicable.', max_length=255)),
                ('point4', models.CharField(default='Multiple Technology Solutions — CCTV, biometric attendance, GPS tracking and cash counting requirements can be addressed through one technology solutions provider.', max_length=255)),
                ('point5', models.CharField(default='Clear Communication — We explain relevant product features, setup requirements and service considerations in a straightforward way.', max_length=255)),
                ('point6', models.CharField(default='Ongoing Support — When a system requires assistance after installation, we can help identify the appropriate service or maintenance requirement.', max_length=255)),
            ],
            options={
                'verbose_name': 'Why Choose Zero Ones',
                'verbose_name_plural': 'Why Choose Zero Ones',
            },
        ),
    ]
