# Generated by Django 6.1 on 2026-09-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_whychoosesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='seo_description',
            field=models.TextField(default='CCTV camera installation, security cameras, GPS vehicle tracking, biometric attendance & cash counting machines in Madurai. Explore suitable security solutions from Zero Ones.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='seo_title',
            field=models.CharField(default='CCTV Installation & Security Solutions in Madurai | Zero Ones', max_length=255),
        ),
    ]
