# Generated by Django 6.1 on 2026-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_sitesetting_seo_description_sitesetting_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='CCTV cameras, biometric attendance, GPS vehicle tracking and cash counting machines for homes, shops, offices and businesses in Madurai.'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_button_label',
            field=models.CharField(default='Get a Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_button_label',
            field=models.CharField(default='Explore Our Solutions', max_length=100),
        ),
    ]
