# Generated by Django 6.1 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_herosection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='values',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='approach',
            field=models.TextField(default='Understand → Recommend → Install → Configure → Support'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='extended_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='local_cta',
            field=models.TextField(default="Tell us your requirement. We'll help you find a suitable solution."),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='local_description',
            field=models.TextField(default='Need a security or technology solution for your home or business? Zero Ones provides CCTV installation, GPS vehicle tracking, biometric and cash counting solutions in Madurai.'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='local_heading',
            field=models.CharField(default='Looking for a Local Solution?', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='mission',
            field=models.TextField(default='To provide practical, reliable and requirement-focused security and technology solutions that help homes, workplaces and businesses choose, install and use suitable technology with confidence.'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='vision',
            field=models.TextField(default='To become a trusted technology solutions provider in Madurai, known for practical security, attendance, vehicle tracking and business technology solutions supported by clear guidance and dependable service.'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='CCTV & Security Solutions for Homes and Businesses in Madurai', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='CCTV & Security Solutions for Homes and Businesses in Madurai', max_length=255),
        ),
    ]
