# Generated by Django 6.1 on 2026-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_aboutsection_values_aboutsection_approach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='CCTV Installation & Technology Support in Madurai', max_length=255)),
                ('description', models.TextField(default='Selecting a product is only the first step. Proper installation, setup, configuration and relevant support help ensure that the selected technology is prepared according to the site and usage requirements.')),
                ('introduction', models.TextField(default='Zero Ones provides relevant installation and technical support across its core security and technology solutions.')),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Section',
            },
        ),
    ]
